name: storj-up
services:
  postgres:
    command:
    - postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: master
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: "5432"
      protocol: tcp
  redis:
    command:
    - redis-server
    deploy:
      replicas: 1
    image: redis:6.0.9
    networks:
      default: null
  satellite-api:
    command:
    - satellite
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/satellite-api/
    deploy:
      replicas: 1
    environment:
      STORJUP_ROLE: satellite-api
      STORJ_ADDRESS: 0.0.0.0:7777
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:10000
      STORJ_CONSOLE_AUTH_TOKEN_SECRET: my-suppa-secret-key
      STORJ_CONSOLE_EXTERNAL_ADDRESS: http://localhost:10000/
      STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL: http://localhost:8888
      STORJ_CONSOLE_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_OPEN_REGISTRATION_ENABLED: "true"
      STORJ_CONSOLE_PUBLIC_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_RATE_LIMIT_BURST: "10000"
      STORJ_CONSOLE_SIGNUP_ACTIVATION_CODE_ENABLED: "false"
      STORJ_CONTACT_EXTERNAL_ADDRESS: satellite-api:7777
      STORJ_DATABASE: postgres://postgres@postgres:5432/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/satellite-api/
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=0
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <storj-up@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_METAINFO_DATABASE_URL: tidb://root@tidb:4000/metainfo?parseTime=true
      STORJ_METAINFO_RATE_LIMITER_ENABLED: "false"
      STORJ_METAINFO_RS_MIN: "1"
      STORJ_METAINFO_RS_REPAIR: "2"
      STORJ_METAINFO_RS_SUCCESS: "3"
      STORJ_METAINFO_RS_TOTAL: "4"
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_OVERLAY_NODE_MINIMUM_DISK_SPACE: 500MB
      STORJ_OVERLAY_NODE_NEW_NODE_FRACTION: "1"
      STORJ_OVERLAY_NODE_SELECTION_CACHE_STALENESS: 5s
      STORJ_ROLE: satellite-api
      STORJ_SERVER_ADDRESS: 0.0.0.0:7777
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:5559
      STORJ_SERVER_REVOCATION_DBURL: redis://redis:6379?db=1
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_USE_PREDEFINED_IDENTITY: "1"
      STORJ_VERSION_RUN_MODE: disable
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_DB: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 7777
      published: "7777"
      protocol: tcp
    - mode: ingress
      target: 10000
      published: "10000"
      protocol: tcp
  storagenode1:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30000
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode1:30001
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30001
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30002
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 30000
      published: "30000"
      protocol: tcp
  storagenode2:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30010
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode2:30011
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30011
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30012
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 30010
      published: "30010"
      protocol: tcp
  storagenode3:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30020
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode3:30021
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30021
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30022
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 30020
      published: "30020"
      protocol: tcp
  storagenode4:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30030
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode4:30031
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30031
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30032
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 30030
      published: "30030"
      protocol: tcp
  storagenode5:
    command:
    - storagenode
    - run
    - api
    - --defaults=dev
    - --identity-dir=/storj/.local/share/storj/identity/storagenode/
    deploy:
      replicas: 1
    environment:
      STORJUP_AUTHSERVICE: http://authservice:8888
      STORJUP_ROLE: storagenode
      STORJUP_SATELLITE: satellite-api
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30040
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode5:30041
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30041
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30042
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://localhost:8080
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/storj/up/storj:1.158.2
    networks:
      default: null
    ports:
    - mode: ingress
      target: 30040
      published: "30040"
      protocol: tcp
  tidb:
    command:
    - -config=/etc/tidb.toml
    deploy:
      replicas: 1
    image: pingcap/tidb:v8.5.6
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4000
      published: "4000"
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/shivam/dev/storj/storj-uplink-nodejs-mcp/storj-uplink-mcp/infra/dev/tidb.toml
      target: /etc/tidb.toml
      bind: {}
    - type: bind
      source: /Users/shivam/dev/storj/storj-uplink-nodejs-mcp/storj-uplink-mcp/infra/dev/tidb-init.sql
      target: /etc/tidb-init.sql
      bind: {}
networks:
  default:
    name: storj-up_default
