#!/usr/bin/env bash
# Local Storj network for developing and testing storj-uplink-mcp without
# touching the real Storj network.  Built on storj-up, the tool Storj uses
# for its own CI (https://github.com/storj/up).
#
#   infra/dev/storj-local.sh up           start satellite + 10 storage nodes,
#                                         mint credentials into infra/dev/.env
#   infra/dev/storj-local.sh status       container status
#   infra/dev/storj-local.sh credentials  (re)mint credentials only
#   infra/dev/storj-local.sh mcp          run the MCP server in the network
#                                         (stdio; for an MCP client config)
#   infra/dev/storj-local.sh e2e          end-to-end tool test against the
#                                         local network via the MCP image
#   infra/dev/storj-local.sh logs [svc]   follow logs
#   infra/dev/storj-local.sh down         stop and delete the local Storj
#                                         data (compose project storj-up ONLY)
#   infra/dev/storj-local.sh regenerate   re-create docker-compose.yaml with
#                                         storj-up (needs Go: go install
#                                         storj.io/storj-up@main)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Everything is scoped to ONE compose project.  `down -v` therefore only ever
# removes containers/volumes labelled com.docker.compose.project=storj-up —
# never anything from other projects on this machine (self-hosted databases,
# other dev stacks).  The guard below refuses to run if that ever changes.
PROJECT="storj-up"
COMPOSE=(docker compose -p "$PROJECT" -f "$HERE/docker-compose.yaml" -f "$HERE/docker-compose.mcp.yml")
ENV_FILE="$HERE/.env"
SATELLITE_IN_NETWORK="satellite-api:7777"

log() { printf '[storj-local] %s\n' "$*" >&2; }

# IANA name of the host's zone (macOS and most Linux link /etc/localtime into a zoneinfo tree).
host_time_zone() {
  local tz; tz="$(readlink /etc/localtime 2>/dev/null | sed -n 's#.*/zoneinfo/##p')"
  echo "${tz:-UTC}"
}

require_compose_file() {
  [[ -f "$HERE/docker-compose.yaml" ]] || { log "docker-compose.yaml missing — run: $0 regenerate"; exit 1; }
  local declared
  declared="$(sed -n 's/^name: *//p' "$HERE/docker-compose.yaml" | head -1)"
  [[ "$declared" == "$PROJECT" ]] || { log "refusing: docker-compose.yaml declares project '${declared:-<none>}', expected '$PROJECT'"; exit 1; }
}

ensure_env_placeholder() {
  # compose refuses to start when an env_file is missing, even for other services
  [[ -f "$ENV_FILE" ]] || printf '# filled by storj-local.sh credentials\n' > "$ENV_FILE"
}

wait_for_satellite() {
  log "waiting for the satellite console (localhost:10000)…"
  for _ in $(seq 1 120); do
    if curl -fsS -o /dev/null http://localhost:10000/ 2>/dev/null; then log "satellite is up"; return 0; fi
    sleep 2
  done
  log "satellite did not come up in time; check: $0 logs satellite-api"; exit 1
}

credentials() {
  require_compose_file
  # storj-up is bundled in the satellite image; running it *inside* the network
  # yields an access grant whose satellite address (satellite-api:7777) is
  # reachable from the MCP container.
  log "minting credentials inside the satellite container…"
  local out
  out="$("${COMPOSE[@]}" exec -T satellite-api storj-up credentials -e -s "$SATELLITE_IN_NETWORK" -c localhost:10000)"
  local grant
  grant="$(printf '%s\n' "$out" | sed -n 's/^export STORJ_ACCESS=//p' | head -1)"
  [[ -n "$grant" ]] || { log "could not parse an access grant from storj-up output:"; printf '%s\n' "$out" >&2; exit 1; }
  {
    echo "# Local storj-up network credentials — development only, regenerated by storj-local.sh"
    echo "# Satellite: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@$SATELLITE_IN_NETWORK"
    echo "STORJ_ACCESS_GRANT=$grant"
    echo "UPLINK_LOG_LEVEL=error"
    echo "STORJ_MCP_TIMEZONE=$(host_time_zone)"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log "wrote $ENV_FILE"
}

case "${1:-}" in
  up)
    require_compose_file; ensure_env_placeholder
    # every service of the generated network; the mcp overlay service is run on demand
    # (bash 3.2 on macOS: no mapfile; service names never contain spaces)
    # shellcheck disable=SC2046
    "${COMPOSE[@]}" up -d --quiet-pull $("${COMPOSE[@]}" config --services | grep -vx mcp)
    wait_for_satellite
    credentials
    log "ready. Next: $0 e2e   or   $0 mcp"
    ;;
  status)      require_compose_file; ensure_env_placeholder; "${COMPOSE[@]}" ps ;;
  credentials) ensure_env_placeholder; credentials ;;
  mcp)         require_compose_file; exec "${COMPOSE[@]}" run --rm -T mcp ;;
  e2e)         require_compose_file; exec node "$HERE/e2e.mjs" ;;
  logs)        require_compose_file; ensure_env_placeholder; shift; "${COMPOSE[@]}" logs -f "$@" ;;
  down)
    require_compose_file; ensure_env_placeholder
    # -v removes only the volumes of project "$PROJECT" (the local satellite/nodes).
    # Never use `docker volume prune` or `docker system prune --volumes` here.
    "${COMPOSE[@]}" down -v --remove-orphans
    rm -f "$ENV_FILE"; log "stopped; local Storj data removed (project $PROJECT only)"
    ;;
  regenerate)
    command -v storj-up >/dev/null || { log "storj-up not found. Install: go install storj.io/storj-up@main (adds ~/go/bin/storj-up; @main because tagged releases still point at the retired img.dev.storj.io registry)"; exit 1; }
    ( cd "$HERE" && rm -f docker-compose.yaml && storj-up init db,minimal \
      && for kv in STORJ_METAINFO_RS_MIN=1 STORJ_METAINFO_RS_REPAIR=2 STORJ_METAINFO_RS_SUCCESS=3 STORJ_METAINFO_RS_TOTAL=4; do
           storj-up env setenv satellite-api "$kv"; done \
      && node slim.mjs )
    log "regenerated $HERE/docker-compose.yaml — review the diff before committing"
    ;;
  *) sed -n '2,20p' "$0"; exit 1 ;;
esac
